---
abstract: 'Interface to Gd Graphics Library'
author:
  - 'Lincoln Stein (lstein@cshl.org)'
build_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GD
no_index:
  directory:
    - t
    - inc
requires:
  Math::Trig: 0
version: 2.53
x_repository:
  type: git
  url: git://github.com/lstein/Perl-GD.git
  web: https://github.com/lstein/Perl-GD
