name: testsuite

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  ubuntu:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: perl -V
      - run: |
          sudo apt update -y
          sudo apt install -y libgd-dev
      - name: install cpan deps
        uses: perl-actions/install-with-cpm@b7eeb5ea204d9c9bd434e01162ae97629cf7fa36 # v2.4
        with:
          install: |
            ExtUtils::PkgConfig
            File::Which
            Math::Trig
            Class::XSAccessor
            Text::CSV_XS
            List::MoreUtils
            Algorithm::Diff
            Test::Kwalitee
            Test::Pod
            Pod::Spell::CommonMistakes
            Test::Fork
            Test::NoWarnings
      # GH #55, libtiff broken on this vm
      - run: perl Makefile.PL --without tiff
      - run: make test

  linux:
    name: "perl ${{ matrix.perl-version }}"
    needs: [ubuntu]
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          [
            "5.44",
            "5.42",
            "5.40",
            "5.38",
            "5.36",
            "5.34",
            "5.32",
            "5.30",
            "5.28",
            "5.26",
            "5.24",
            "5.22",
            "5.20",
            "5.18",
            "5.16",
            "5.14",
            "5.12",
            "5.10",
            "5.8",
          ]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: shogo82148/actions-setup-perl@53e33bb27be492a926eee378e8a5f7ff6618b061 # v1.43.1
        with:
          perl-version: ${{ matrix.perl-version }}
      - run: perl -V
      - run: |
          sudo apt update -y
          sudo apt install -y libgd-dev
      - name: install cpanm
        run: curl -sL https://cpanmin.us | perl - App::cpanminus
      - name: install cpan deps
        run: cpanm --notest ExtUtils::PkgConfig File::Which Math::Trig Test::NoWarnings
      # GH #55, libtiff broken on this vm
      - run: perl Makefile.PL --without tiff
      - run: make test

  macOS:
    needs: [ubuntu]
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: macOS-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: [latest]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: perl -V
        # already installed
      - run: brew install gd
      - name: install cpan deps
        uses: perl-actions/install-with-cpm@b7eeb5ea204d9c9bd434e01162ae97629cf7fa36 # v2.4
        with:
          install: |
            ExtUtils::PkgConfig
            File::Which
            Math::Trig
            Test::Fork
            Test::NoWarnings
      - run: perl Makefile.PL
      - run: make test

  windows:
    needs: [ubuntu]
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 0
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 0
      VCPKG_DEFAULT_TRIPLET: x64-windows

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: [latest]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: perl -V
      #- id: cache-vcpkg
      #  uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      #  with:
      #    path: |
      #      ${{ github.workspace }}/vcpkg/packages
      #      D:/a/_temp/vcpkg_cache
      #    key: vcpkg-${{ runner.image }}-${{ env.RUNNER_IMAGE_VERSION }}
      #- run: choco install -y libgd
      #- name: choco install libgd
      #  uses: crazy-max/ghaction-chocolatey@2526f467ccbd337d307fe179959cabbeca0bc8c0 # v3.4.0
      #  with:
      #    args: install -y libgd
      #- run: vcpkg install libgd
      # too slow: echo.set(VCPKG_BUILD_TYPE release) >> d:\vcpkg\triplets\x64-windows.cmake
      #  or install the msys2 perl-gd library
      # vcpkg needs 7m, but is cached
      - name: vcpkg install libgd
        uses: johnwason/vcpkg-action@04c68c847bf5196ecaa72331ecf51208583916ef # v8.0.0
        id: vcpkg
        with:
          pkgs: libgd
          triplet: x64-windows-release
          token: ${{ github.token }}
      - name: install cpan deps
        uses: perl-actions/install-with-cpm@b7eeb5ea204d9c9bd434e01162ae97629cf7fa36 # v2.4
        with:
          sudo: false
          install: |
            ExtUtils::PkgConfig
            File::Which
            Math::Trig
            Test::Fork
            Test::NoWarnings
      - run: dir /s "vcpkg/packages/libgd_x64-windows-release"
        shell: cmd
      - run: perl Makefile.PL --lib_gd_path ${{ github.workspace }}/vcpkg/packages/libgd_x64-windows-release/lib --without png
        env:
          PKG_CONFIG_PATH: ${{ github.workspace }}/vcpkg/packages/libgd_x64-windows-release/lib
      - run: perl -pi -e's/-Wl,--enable-auto-image-base/ /' Makefile
      - run: make test TEST_VERBOSE=1 2>&1 | tee make.log
        continue-on-error: true
      - name: Upload Failure
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: artifacts
          path: .
