name: testsuite

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  ubuntu:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: perl -V
      - run: sudo apt install libgd-dev
      - name: install cpan deps
        uses: perl-actions/install-with-cpm@v1.3
        with:
          install: |
            ExtUtils::PkgConfig
            Math::Trig
            Class::XSAccessor
            Text::CSV_XS
            List::MoreUtils
            Algorithm::Diff
            Test::Kwalitee
            Test::Pod
            Pod::Spell::CommonMistakes
            Test::Fork
            Test::NoWarnings
      - run: perl Makefile.PL
      - run: make test

  linux:
    name: "perl ${{ matrix.perl-version }}"
    needs: [ubuntu]
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          [
            "5.34",
            "5.32",
            "5.30",
            "5.28",
            "5.26",
            "5.24",
            "5.22",
            "5.20",
            "5.18",
            "5.16",
            "5.14",
            "5.12",
            "5.10",
            "5.8",
          ]

    steps:
      - uses: actions/checkout@v1
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
      - run: perl -V
      - run: sudo apt install libgd-dev
      - name: install cpan deps
        uses: perl-actions/install-with-cpm@v1.3
        with:
          sudo: false
          install: |
            ExtUtils::PkgConfig
            Math::Trig
            Test::NoWarnings
      - run: perl Makefile.PL
      - run: make test

  macOS:
    needs: [ubuntu]
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: macOS-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: [latest]

    steps:
      - uses: actions/checkout@v1
      - run: perl -V
        # already installed
      - run: brew install gd
      - name: install cpan deps
        uses: perl-actions/install-with-cpm@v1.3
        with:
          install: |
            ExtUtils::PkgConfig
            Math::Trig
            Test::Fork
            Test::NoWarnings
      - run: perl Makefile.PL
      - run: make test

  windows:
    needs: [ubuntu]
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 0
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 0
      VCPKG_DEFAULT_TRIPLET: x64-windows

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: [latest]

    steps:
      - uses: actions/checkout@master
      - run: perl -V
      #- run: vcpkg install libgd
      # too slow: echo.set(VCPKG_BUILD_TYPE release) >> d:\vcpkg\triplets\x64-windows.cmake
      #  or install the msys2 perl-gd library
      - name: install cpan deps
        uses: perl-actions/install-with-cpm@v1.3
        with:
          sudo: false
          install: |
            ExtUtils::PkgConfig
            Math::Trig
            Test::Fork
            Test::NoWarnings
            GD
      - run: perl Makefile.PL
      - run: perl -pi -e's/-Wl,--enable-auto-image-base/ /' Makefile
      - run: make test TEST_VERBOSE=1 2>&1 | tee make.log
        continue-on-error: true
      - name: Upload Failure
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: artifacts
          path: .
